
package com.vijay.handler;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerInfo", targetNamespace = "http://handler.vijay.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
@HandlerChain(file="handler-chain.xml")
public interface ServerInfo {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://handler.vijay.com/", className = "com.vijay.handler.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://handler.vijay.com/", className = "com.vijay.handler.GetNameResponse")
    @Action(input = "http://handler.vijay.com/ServerInfo/getNameRequest", output = "http://handler.vijay.com/ServerInfo/getNameResponse")
    public String getName();

}
